spring:
  jpa:
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
      hibernate.hbm2ddl.auto: create
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/telegram_bot"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: "jdbc:postgresql://localhost:5432/telegram_bot"
    driver-class-name: org.postgresql.Driver

server:
      port: 8081

telegram:
    bot-name: CitiesInfo_bot
    token: 1895037071:AAH2hag5f-PbBYpq_zr3Yzv4wGJ9yyYIp_4


